type Todo {
  task: String!
  completed: Boolean!
  owner: User!
}

type Monday {
  event: String!
  owner: User!
}

type Tuesday {
  event: String!
  owner: User!
}

type Wednesday {
  event: String!
  owner: User!
}

type Thursday {
  event: String!
  owner: User!
}

type Friday {
  event: String!
  owner: User!
}

type Saturday {
  event: String!
  owner: User!
}

type Sunday {
  event: String!
  owner: User!
}

type User {
  email: String! @unique
  todos: [Todo!] @relation
  mondays: [Monday!] @relation
  tuesdays: [Tuesday!] @relation
  wednesdays: [Wednesday!] @relation
  thursdays: [Thursday!] @relation
  fridays: [Friday!] @relation
  saturdays: [Saturday!] @relation
  sundays: [Sunday!] @relation
}

type Query {
  allTodos: [Todo!]
  allMondays: [Monday!]
  allTuesdays: [Tuesday!]
  allWednesdays: [Wednesday!]
  allThursdays: [Thursday!]
  allFridays: [Friday!]
  allSaturdays: [Saturday!]
  allSundays: [Sunday!]
}
